import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS With Tailwind Theme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center items-center">
        <h1 className="text-2xl">
          NEXT JS Template For Toggling themes using Tailwind CSS
        </h1>
      </main>
    </div>
  );
};

export default Home;
